services:
  postgres:
    image: postgres:15
    container_name: postgres_contabilidade
    restart: always
    environment:
      POSTGRES_USER: cleber
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crud_contabilidade
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  backend:
    container_name: backend_contabilidade
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://cleber:123456@postgres:5432/crud_contabilidade
    networks:
      - app_net

  frontend:
    container_name: frontend_contabilidade
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: crud_contabilidade/frontend:latest
    expose:
      - "9000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_net

  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
